volumes:
  db:
    driver: local

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - type: volume
        source: db
        target: /var/lib/postgrsql/data
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./src
        target: /src
